export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";

export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

